workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api.eu1.stackone.com/oas/stackone.json
            - location: https://api.eu1.stackone.com/oas/hris.json
            - location: https://api.eu1.stackone.com/oas/ats.json
            - location: https://api.eu1.stackone.com/oas/crm.json
            - location: https://api.eu1.stackone.com/oas/iam.json
            - location: https://api.eu1.stackone.com/oas/marketing.json
            - location: https://api.eu1.stackone.com/oas/lms.json
            - location: https://api.eu1.stackone.com/oas/ticketing.json
            - location: https://api.eu1.stackone.com/oas/documents.json
        registry:
            location: registry.speakeasyapi.dev/stackone/stackone/my-source
targets:
    my-first-target:
        target: postman
        source: my-source
